services:
  sochief-db:
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"

  sochief-api:
    environment:
      SPRING_PROFILES_ACTIVE: local

  minio:
    ports:
      - ${MINIO_PORT}:9000   # API
      - ${MINIO_INTERFACE_PORT}:9001   # Console
    command: server /data --console-address ":9001"
