networks:
  sochief_net:

volumes:
  db_data:

services:
  sochief-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - sochief_net

  sochief-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sochief-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080

      POSTGRES_HOST: sochief-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    ports:
      - "${APP_PUBLIC_API_EXPOSED_PORT}:8080"
    restart: unless-stopped
    networks:
      - sochief_net
