spring:
  application:
    name: sochief-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    enabled: true
    withCredentials: true
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
  api-docs:
    enabled: true

minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

# ========= LOCAL =========
---

spring:
  config:
    activate:
      on-profile: local

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
